services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/abe/docker-apps/jellyfin/config:/config
      - /home/abe/docker-apps/jellyfin/cache:/cache
      - type: bind
        source: /home/abe/data/media
        target: /media
    restart: 'unless-stopped'
    # Optional: set your public URL if needed
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://your-public-url:8096
    extra_hosts:
      - 'host.docker.internal:host-gateway'
